import '@/styles/globals.css'
import { Header } from "@/components"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen">
          <Header />
          <div className="bg-gray-100">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
